### ISSUE TITLE
Error when starting

### ISSUE THREAD

**Issue by drphero** [pinokiofactory/mlx#1]
When trying to run chat-with-mlx, I get the following error. I checked and huggingface_hub is installed in the environment.

```
Traceback (most recent call last):
  File "/Users/brent/pinokio/api/mlx.git/app/env/bin/chat-with-mlx", line 5, in <module>
    from chat_with_mlx.app import main
  File "/Users/brent/pinokio/api/mlx.git/app/chat_with_mlx/app.py", line 10, in <module>
    from mlx_lm import load, stream_generate, generate
  File "/Users/brent/pinokio/api/mlx.git/app/env/lib/python3.10/site-packages/mlx_lm/__init__.py", line 3, in <module>
    from .utils import convert, generate, load, stream_generate
  File "/Users/brent/pinokio/api/mlx.git/app/env/lib/python3.10/site-packages/mlx_lm/utils.py", line 17, in <module>
    from huggingface_hub.utils._errors import RepositoryNotFoundError
ModuleNotFoundError: No module named 'huggingface_hub.utils._errors'
```

**Comment by emircanerkul** [comment]
+1 same with mac m1 15 ModuleNotFoundError: No module named 'huggingface_hub.utils._errors'
